gvanem/Watt-32

- src/target.h
Don't use memory models macros for target architecture identification
Now `__SMALL__` macro work with 16-bit and 32-bit architecture
Confusing `__SMALL32__` macro is useless now
> Better identification of 16/32/64-bit targets

- src/lang.l
valid warning level is 0-4 and level 5 is for disabling warning
it is checked for Open Watcom 2.0
> correct warning level for WATCOM

- src/wattcp.h
64-bit type is defined for all WATCOM compilers and it doesn't depend on memory model etc.
> correct WATCOM 64-bit type usage

- src/makefile.all
Some DOS extenders use small memory model instead of flat memory model that 32-bit small memory model is useful
> add 32-bit SMALL memory model for WATCOM

- src/version.c
I forgot add proper location for configuration file if 32-bit small model is used
> correct omission for WATCOM 32-bit small memory model

- src/makefile.all
This way standard libraries have lowest priority that can be simply override if necessary
priority is lower then #pragma library priority
> Watcom add standard libraries required for linking into each modules

- src/sock_ini.c
This info is now in each module (by -zlf compiler option) that need not be specified anywhere
> WATCOM remove #pragma library as useless

- src/makefile.all
-zw option is for Windows 3.x applications
it create `__WINDOWS__` macro which  overwrite `__NT__` macro and completely confuse Windows header files and code.
This option need not be used for `WIN32` API
> fix a bug in WATCOM options

- src/makefile.all
.ERASE directive is global repeated use has no sense
MAKEFIL macro is replaced by wmake internal macro `__MAKEFILES__` which contains list of all loaded(used) makefiles
> small optimization for Watcom make files

- appveyor-script.bat
- appveyor-script.py
- bin/djcommon.mak
- bin/djgpp_win.mak
- src/configur.bat
- src/configur.sh
- src/makefile.all
- util/dj-errno.mak
Here are some patches that should make cross-compiling to djgpp a less confusing experience:
* It is now possible to use `configur.sh` from a Bash shell under mingw-w64/MSYS2.
* `BIN_PREFIX` is detected automatically and written to the makefile.  The compiler should just be in the user's `PATH`.  If someone does need to specify the full path, this can still be done by setting `DJGPP_PREFIX` before calling `configur.sh`
* `W32_NASM_` and `W32_BIN2C_` are written to the makefile. (why do these have underscores for djgpp, but not for other platforms?)
* `dj_errno.exe` can be cross-compiled by setting `BIN_PREFIX` before calling `make`.
* `mkmake` is called with `FLAT` so that `PKT_STUB` is defined for djgpp.
> Cross-compilation improvements

- inc/netinet/tcp.h
I checked all headers to see if they would compile on their own.  This is the only one that was missing some includes.
> Add missing includes in <netinet/tcp.h> [fixes #59]

- bin/finger.c
- bin/host.c
- inc/sys/cdefs.h
- inc/sys/swap.h
- inc/sys/syslog.h
- src/misc.c
- src/syslog.c
- src/winadinf.c
Observations:
* `MS_CDECL` and `W32_CDECL` are *always* identical.
* `W32_CDECL` is only used for one single function (`syslog()`).
Therefore, we can use `MS_CDECL` for this function too and repurpose `W32_CDECL` for what is currently `cdecl`.
`cdecl` is also used a lot in `src/`, but `src/target.h` already defines `cdecl` too.  So we don't need to change anything there.
> replace 'cdecl' with 'W32_CDECL' [fixes #60]

- .gitignore
- util/makefile
The usual method to find system libraries on these platforms to is via `pkg-config`.
Makefile variables that are set with '`=`' are only evaluated when used, so this shouldn't cause problems when compiling on DOS.
> Use pkg-config to find S-Lang on Linux/MinGW

- src/configur.sh
The `{3..7}` syntax appears to be Bash-specific and does not work if
`/bin/sh` is not actually Bash.  Using `seq` should be more portable.
> Fix detecting DJGPP_PREFIX in configur.sh

- src/makefile.all
- util/sysdep.h
In my djgpp build scripts I try to support MacOS.  I don't have a Mac so I have to rely on running test builds via Github Actions...
Currently it fails to build Watt-32 due to:
```
gcc -Wall -g -save-temps  -I/usr/local/Cellar/s-lang/2.3.2/include -o linux/mkmake mkmake.c -L/usr/local/Cellar/s-lang/2.3.2/lib -lslang
gcc -Wall -g -save-temps  -o linux/mkdep mkdep.c
gcc -Wall -g -save-temps  -o linux/mklang mklang.c
In file included from mkdep.c:15:
./sysdep.h:64:4: error: "Unsupported platform or cross-combo"
#error "Unsupported platform or cross-combo"
^
1 error generated.
make: *** [linux/mkdep] Error 1
make: *** Waiting for unfinished jobs....
In file included from mklang.c:4:
./sysdep.h:64:4: error: "Unsupported platform or cross-combo"
#error "Unsupported platform or cross-combo"
^
1 …
```
> MacOS build fixes

- inc/sys/cdefs.h
- inc/sys/ioctl.h
When the include path contains the Watt-32 header directory multiple times, `#include_next` breaks, since two headers have it located inside the include guard.
This scenario can happen when a project builds a local copy of Watt-32, but the user has their own copy in the global include path already.  In this case we want to use the local version of the header, so the recursive `#include_next` must be placed at the end of the header file.
> Handle recursive `include_next`

- inc/sys/uio.h
- inc/sys/wtypes.h
- src/receive.c
- src/transmit.c
This exposes libc's `readv()`/`writev()` again.  `iov_len` must be made `size_t` to be compatible.
> Include djgpp's <sys/uio.h>

- src/receive.c
- src/transmit.c
Now returns EINVAL, and also checks if the sum of all `iov_len`s stays below INT_MAX.  The loops are split in two, to ensure that all iovecs are valid before any bytes are received/transmitted.
> Fix `iov_len` overflow checks

- inc/sys/socket.h
- src/ioctl.c
Eliminates the need to do explicit `(char*)` casts, so the syntax is similar to `ioctl()` with varargs.  Should be fully backwards compatible.
Not strictly necessary, but it will tidy things up a bit.  Let me know what you think.
> Change `ioctlsocket()` argument to `void*`

- src/receive.c
- src/transmit.c
Forgot something in #80.  We should call `usr_yield` when in a tight loop.
> Yield while waiting for `connect()` to finish

- src/misc.h
I just noticed these macros, I'm surprised this hasn't caused any trouble yet.  Or maybe it has, it just would be very hard to debug.  At least in gcc, modifying the stack pointer in an asm block is very risky.  I don't know how well the other compilers cope with this.
A safer solution is to keep the stack pointer in the same place, and store the flags someplace where the compiler can see them, in a variable.
> Fix unsafe `PUSHF_CLI`/`POPF` macros for gcc

- src/connect.c
- src/pctcp.c
- src/pctcp.h
- src/socket.c
- src/transmit.c
Noticed this while working on #80.  For non-`SOCK_STREAM` sockets, it should be possible to rebind the destination address by calling `connect()` again.
https://man7.org/linux/man-pages/man2/connect.2.html
> Some protocol sockets (e.g., UNIX domain stream sockets) may
> successfully connect() only once.
> 
> Some protocol sockets (e.g., datagram sockets in the UNIX and
> Internet domains) may use connect() multiple times to change
> their association.
Not tested, but it should work since I just copied the code from `transmit.c`.
> `connect()`: Allow non-TCP sockets to rebind `remote_addr`

- src/pcbuf.c
Just noticed this potential issue.  `sock_setbuf()` is used for both TCP and UDP sockets, but the default buffer size for TCP is larger than for UDP.
> Fix incorrect buffer size used in `sock_setbuf()`

- src/configur.sh
This doesn't seem to be used anywhere, no point in keeping it.
> Remove `$WATT_ROOT` check in `configur.sh`

- src/select.c
Fixed Watcom linking error when program makes use of `select_s` but `W32_NO_8087` has been defined
```
Error! E2028: _w32_timeval_diff_ is an undefined reference
```
To replicate the problem: checkout adeb8e011d4499c2c4d876b1078e339add992461 and build `WATTCPWL.LIB` with `#define USE_BSD_API` then link the following test program against it
```c
/* Compile with `OWCC -I INC LIB\WATTCPWL.LIB TEST.C` */
#include <stdio.h>
#include <stdlib.h>
#include <sys/select.h>
void foo(void) {
/* Isn't run, just testing select() can be linked */
select(0, NULL, NULL, NULL, NULL);
}
int main (int argc, char *argv[]) {
puts("I compiled!");
return 0;
}
```
> Made 'select_s' compile correctly when build defines 'W32_NO_8087'

- src/select.c
Small addition to #87.  Possible alternative: Use a flag in `_sock_crit_stop()` to only run daemon if it was missed previously.
Also some minor improvements to comments and code style.
> Avoid running daemon on every loop in `select_s()`/`poll()`

- src/shutdown.c
Ran into this recently when I made a websocket server using Boost.  After any `shutdown()` is called, the next operation always fails with `ESHUTDOWN`.
What happens is: when the WS client sends a "close" header, the server (Boost code) calls `shutdown(SHUT_WR)` to send FIN, then continues to `recv()` the rest of the message.  But it gets confused due to the error, so WS sessions never terminate cleanly.
Simple solution is to not set `so_error`.  Note that this does remove all current uses of `ESHUTDOWN`.
Would also be nice if `shutdown()` could actually send the FIN.  I think most code from `close_s()` can be moved here.
> Don't set `so_error` in `shutdown()`

- src/select.c
Some more tweaks to `poll()`/`select_s()`:
* If we get interrupted by a signal, but already have one or more ready sockets, that should not be an error.
* Yield should happen at the end of a loop (only if there is no reason to return yet). Also, no need to `tcp_tick()` twice in one loop.
* Then, I think the short-timeout hack for WinXP can be removed.  If yield does stall, then the next loop will return some result.
> More improvements in select.c

- src/run.c
Found the DHCP/daemon problem.  The timer was being reset every time `daemon_run()` was called, and therefore would never actually trigger.
What I don't understand, is why this only caused problems on 16-bit systems...
Fixes: #4
> Fix daemon timer

- src/pcdhcp.c
Was looking into the DHCP issue (#4) and noticed this potential improvement (that you already hinted at).  While waiting for a DHCP response, we can call `dhcp_fsm()` directly, and then later install it as a daemon for lease renewal.  On my network, this speeds up DHCP configuration from ~4 seconds to almost-instantaneous.
This may appear to "fix" #4, but does not solve the underlying issue (that daemon processes seemingly won't run on 16-bit).
> Speed up DHCP bootstrap

- src/receive.c
- src/transmit.c
Just noticed this potential bug.
When reading or writing multiple iovecs, if an error occurs after the first one, the byte count of the previous successful operation is discarded.
In the case of `EWOULDBLOCK`, the application will try again, and will end up sending duplicate output or discarding valid input.  It is safer to return -1 only if nothing was transmitted.
> Return partial byte count on error in scatter/gather IO functions

- src/pctcp.c
Small tweak here.  Currently `sock_write()` will call `tcp_tick()` and yield even when it has nothing more to send.  There's no need for that.
> `sock_write()`: Skip yield and tcp_tick when already done

- src/pctcp.c
- src/tcp_fsm.c
Introduced in #102 / #103, sorry.
`send_una` should always be positive here, so casting is safe.
> Fix sign-compare warnings

- src/transmit.c
Addition to #101.  After a partial write on a non-blocking socket, we should not try to send the next iovec.  It is very likely that the buffer gets flushed in `tcp_tick()`, and then we end up skipping bytes.  That would be very bad.
> `sendmsg()`/`writev_s()`: Return immediately after partial write

- inc/sys/socket.h
- src/pctcp.c
- src/tcp_fsm.c
- src/transmit.c
This patch reduces the number of segments sent with PUSH bit, so that a receiver is more inclined to use delayed-ACK.
Logic:
* There is no need to set a PUSH bit on an empty segment.
* When sending multiple segments, only the last one needs to have PUSH set.
* PUSH bit is automatically enabled on close (if data pending), or retransmit.
* A non-blocking socket does not set PUSH on a partial write.
* Flushing is controlled by `sock_noflush()` or `TCP_NOPUSH`.  If the user does not want to flush yet, we also don't need to set the PUSH bit.
* Once the PUSH bit is enabled, it is only cleared after the whole buffer is flushed.
In addition, we can borrow `MSG_MORE` from Linux to give the BSD interface more control over this.  This is then also used internally to control flushing of multiple …
> Improve PUSH-bit / flush logic

- src/gettod.c
- src/timer.c
Not sure who Steve is, but he messed up a bit here.
The problem in #99 is that `tv_sec` is set from libc `time()`, while `tv_usec` is set from `microsec_clock()`.  Those two are of course not guaranteed to be synchronized.
Simply putting `#define STEVES_PATCHES 0` is a solution, but removing it altogether makes the code more readable again.
The benchmark (from the other thread) now becomes:
```
hires_timer(0):  3387089559 cycles (avg 45161ns per call)
hires_timer(1):   234681742 cycles (avg  3129ns per call)
USE_RDTSC=1   :    27900545 cycles (avg   372ns per call)
```
> Fix 8254 timer inaccuracy

- src/gettod.c
As I mentioned in #99, the 64-bit divisions can be avoided by using NTP format as intermediate between 8254-ticks and `timeval`.  This can be implemented right now since `microsec_clock()` isn't used anywhere else.
Also fixed is the ~134ms jump at midnight.
On my Pentium 3, the speed difference is not very substantial:
```
Before: avg. 2347-2388 cycles (3129-3184ns) per call
After : avg.      2195 cycles (     2927ns) per call
```
Only ~8% faster.  But slower CPUs will see much more improvement.
Fun fact: the "before" number is variable because gcc does 64-bit division by shift-and-subtract, it gets a little slower for larger values.  So it was fastest just after midnight.
> Avoid 64-bit division in 8254 timer

- src/gettod.c
I was looking to find out how this code works, and see if maybe the `gettimeofday()` call could be replaced with something else.
https://github.com/gvanem/Watt-32/blob/5f72db8e5cfe8e7c701ecc958030b6118af93b6b/src/gettod.c#L363-L399
But it's not clear to me what it's trying to do.  `tick` and `last` are always multiples of 5, so:
```c
corr = abs ((int)last-(int)tick) / 8
= abs (     10  -     15  ) / 8
= 5 / 8
= 0
```
The correction is always zero.  Maybe it does something if you call it less often, say once every second, but that is not how it's used here.  And even then I don't quite see how it relates BIOS ticks to rdtsc ticks.
But then at midnight:
```c
corr = abs ((int)last-(int)tick) / 8
= abs ( 1573035 -     0   ) / 8
= 1573035 / 8
= 196629
```
And it completely breaks.
So I think …
> Disable `adjust_cpu_clock()` in rdtsc timer

- inc/sys/ioctl.h
> Fixed Watcom W135 when compiling for 16-bit processors

- inc/sys/wtypes.h
#75 added `#include <sys/uio.h>` to the DJGPP build of the project. Unfortunately this made the build of DJGPP that ships with FreeDOS 1.3 and SVarDOS fail to build Watt-32 as that header doesn't exist in those versions.
Since the DOS versions of DJGPP identifies as v2.3 and the [gcc12 based cross compiler](https://github.com/andrewwutw/build-djgpp/releases/tag/v3.4) identifies as version 2.5 the quick fix to get building working on DOS again is to check what minor version of DJGPP is being used and fallback when minor version is <= 3.
> Don't include uio.h on DJGPP v2.3

- src/cpuid.c
- src/pcdbug.c
As discussed in #120 this PR replaces instances of `snprintf` with `sprintf` in `cpuid.c` and `pcdbug.c` which allows C89 compilers and linkers without their own `snprintf` extensions to build the library again.
Additionally maximum length these `sprintf` calls can output has been hand calculated and array size adjusted accordingly, resulting in a tiny amount of more free memory.
> Use sprintf to make codebase C89 compliant

- src/misc_str.c
Resolves the type-limits warning in #120 
What DJGPP is saying here makes sense. `VALID_CH` is a macro inclining  `((c) >= -1 && (c) <= 255)` but a `char` can never go higher than `128` while `-1` and `255` are the same on an `unsigned char` the whole test seems redundant, never the less copying the `char` to an `int` as is done in the other `str*` functions silences this error.
> Refactored strltrim so VALID_CH() macro dosen't generate any warnings

- src/gettod.c
Addresses unused function part of #120 report. Function `adjust_cpu_clock` has been disabled due to a midnight bug. Manually stripping out the function with pre-processor commands removes the warning but keeps the source code available in case someone ever wants to fix it.
> Explicitly strip out unused static function 'adjust_cpu_clock'
